// K-star 실데이터 — 공개된 생년월일(위키피디아 등 공개 프로필 기준)로 자체 엔진이 오행을 산출해 매칭.
// 선정 기준: 외국인 타깃 글로벌 인지도(K팝·배우·스포츠). 표기는 글로벌 활동명(로마자) + 그룹 병기.
// 매칭 프레임은 §5.8 공명 톤 + 'for fun' 라벨 — 인물에 대한 사실 주장이 아닌 놀이 콘텐츠.
// 운영·확장은 Airtable(kstars 테이블) 권장: name, birth, gender, image (CLAUDE.md §6.6).
import type { KStar } from '../lib/saju/kstar';

export const KSTARS: readonly KStar[] = [
  // --- K-pop ---
  { id: 'rm', name: 'RM (BTS)', birth: { year: 1994, month: 9, day: 12 }, gender: 'male' },
  { id: 'jin', name: 'Jin (BTS)', birth: { year: 1992, month: 12, day: 4 }, gender: 'male' },
  { id: 'suga', name: 'SUGA (BTS)', birth: { year: 1993, month: 3, day: 9 }, gender: 'male' },
  { id: 'jhope', name: 'J-Hope (BTS)', birth: { year: 1994, month: 2, day: 18 }, gender: 'male' },
  { id: 'jimin', name: 'Jimin (BTS)', birth: { year: 1995, month: 10, day: 13 }, gender: 'male' },
  { id: 'v', name: 'V (BTS)', birth: { year: 1995, month: 12, day: 30 }, gender: 'male' },
  { id: 'jungkook', name: 'Jungkook (BTS)', birth: { year: 1997, month: 9, day: 1 }, gender: 'male' },
  { id: 'jisoo', name: 'Jisoo (BLACKPINK)', birth: { year: 1995, month: 1, day: 3 }, gender: 'female' },
  { id: 'jennie', name: 'Jennie (BLACKPINK)', birth: { year: 1996, month: 1, day: 16 }, gender: 'female' },
  { id: 'rose', name: 'Rosé (BLACKPINK)', birth: { year: 1997, month: 2, day: 11 }, gender: 'female' },
  { id: 'lisa', name: 'Lisa (BLACKPINK)', birth: { year: 1997, month: 3, day: 27 }, gender: 'female' },
  { id: 'nayeon', name: 'Nayeon (TWICE)', birth: { year: 1995, month: 9, day: 22 }, gender: 'female' },
  { id: 'momo', name: 'Momo (TWICE)', birth: { year: 1996, month: 11, day: 9 }, gender: 'female' },
  { id: 'sana', name: 'Sana (TWICE)', birth: { year: 1996, month: 12, day: 29 }, gender: 'female' },
  { id: 'jihyo', name: 'Jihyo (TWICE)', birth: { year: 1997, month: 2, day: 1 }, gender: 'female' },
  { id: 'mina', name: 'Mina (TWICE)', birth: { year: 1997, month: 3, day: 24 }, gender: 'female' },
  { id: 'tzuyu', name: 'Tzuyu (TWICE)', birth: { year: 1999, month: 6, day: 14 }, gender: 'female' },
  { id: 'suho', name: 'Suho (EXO)', birth: { year: 1991, month: 5, day: 22 }, gender: 'male' },
  { id: 'baekhyun', name: 'Baekhyun (EXO)', birth: { year: 1992, month: 5, day: 6 }, gender: 'male' },
  { id: 'chanyeol', name: 'Chanyeol (EXO)', birth: { year: 1992, month: 11, day: 27 }, gender: 'male' },
  { id: 'do', name: 'D.O. (EXO)', birth: { year: 1993, month: 1, day: 12 }, gender: 'male' },
  { id: 'kai', name: 'Kai (EXO)', birth: { year: 1994, month: 1, day: 14 }, gender: 'male' },
  { id: 'sehun', name: 'Sehun (EXO)', birth: { year: 1994, month: 4, day: 12 }, gender: 'male' },
  { id: 'karina', name: 'Karina (aespa)', birth: { year: 2000, month: 4, day: 11 }, gender: 'female' },
  { id: 'winter', name: 'Winter (aespa)', birth: { year: 2001, month: 1, day: 1 }, gender: 'female' },
  { id: 'giselle', name: 'Giselle (aespa)', birth: { year: 2000, month: 10, day: 30 }, gender: 'female' },
  { id: 'ningning', name: 'Ningning (aespa)', birth: { year: 2002, month: 10, day: 23 }, gender: 'female' },
  { id: 'minji', name: 'Minji (NewJeans)', birth: { year: 2004, month: 5, day: 7 }, gender: 'female' },
  { id: 'hanni', name: 'Hanni (NewJeans)', birth: { year: 2004, month: 10, day: 6 }, gender: 'female' },
  { id: 'danielle', name: 'Danielle (NewJeans)', birth: { year: 2005, month: 4, day: 11 }, gender: 'female' },
  { id: 'haerin', name: 'Haerin (NewJeans)', birth: { year: 2006, month: 5, day: 15 }, gender: 'female' },
  { id: 'bangchan', name: 'Bang Chan (Stray Kids)', birth: { year: 1997, month: 10, day: 3 }, gender: 'male' },
  { id: 'hyunjin', name: 'Hyunjin (Stray Kids)', birth: { year: 2000, month: 3, day: 20 }, gender: 'male' },
  { id: 'felix', name: 'Felix (Stray Kids)', birth: { year: 2000, month: 9, day: 15 }, gender: 'male' },
  { id: 'mingyu', name: 'Mingyu (SEVENTEEN)', birth: { year: 1997, month: 4, day: 6 }, gender: 'male' },
  { id: 'vernon', name: 'Vernon (SEVENTEEN)', birth: { year: 1998, month: 2, day: 18 }, gender: 'male' },
  { id: 'wonyoung', name: 'Jang Wonyoung (IVE)', birth: { year: 2004, month: 8, day: 31 }, gender: 'female' },
  { id: 'yujin', name: 'An Yujin (IVE)', birth: { year: 2003, month: 9, day: 1 }, gender: 'female' },
  { id: 'sakura', name: 'Sakura (LE SSERAFIM)', birth: { year: 1998, month: 3, day: 19 }, gender: 'female' },
  { id: 'chaewon', name: 'Kim Chaewon (LE SSERAFIM)', birth: { year: 2000, month: 8, day: 1 }, gender: 'female' },
  { id: 'ryujin', name: 'Ryujin (ITZY)', birth: { year: 2001, month: 4, day: 17 }, gender: 'female' },
  { id: 'iu', name: 'IU', birth: { year: 1993, month: 5, day: 16 }, gender: 'female' },
  { id: 'gdragon', name: 'G-Dragon', birth: { year: 1988, month: 8, day: 18 }, gender: 'male' },
  { id: 'taeyeon', name: 'Taeyeon', birth: { year: 1989, month: 3, day: 9 }, gender: 'female' },
  { id: 'psy', name: 'PSY', birth: { year: 1977, month: 12, day: 31 }, gender: 'male' },
  { id: 'boa', name: 'BoA', birth: { year: 1986, month: 11, day: 5 }, gender: 'female' },
  { id: 'rain', name: 'Rain', birth: { year: 1982, month: 6, day: 25 }, gender: 'male' },
  // --- 배우 ---
  { id: 'leeminho', name: 'Lee Min-ho', birth: { year: 1987, month: 6, day: 22 }, gender: 'male' },
  { id: 'kimsoohyun', name: 'Kim Soo-hyun', birth: { year: 1988, month: 2, day: 16 }, gender: 'male' },
  { id: 'hyunbin', name: 'Hyun Bin', birth: { year: 1982, month: 9, day: 25 }, gender: 'male' },
  { id: 'sonyejin', name: 'Son Ye-jin', birth: { year: 1982, month: 1, day: 11 }, gender: 'female' },
  { id: 'songjoongki', name: 'Song Joong-ki', birth: { year: 1985, month: 9, day: 19 }, gender: 'male' },
  { id: 'songhyekyo', name: 'Song Hye-kyo', birth: { year: 1981, month: 11, day: 22 }, gender: 'female' },
  { id: 'gongyoo', name: 'Gong Yoo', birth: { year: 1979, month: 7, day: 10 }, gender: 'male' },
  { id: 'parkseojun', name: 'Park Seo-jun', birth: { year: 1988, month: 12, day: 16 }, gender: 'male' },
  { id: 'parkbogum', name: 'Park Bo-gum', birth: { year: 1993, month: 6, day: 16 }, gender: 'male' },
  { id: 'suzy', name: 'Bae Suzy', birth: { year: 1994, month: 10, day: 10 }, gender: 'female' },
  { id: 'hansohee', name: 'Han So-hee', birth: { year: 1994, month: 11, day: 18 }, gender: 'female' },
  { id: 'chaeunwoo', name: 'Cha Eun-woo', birth: { year: 1997, month: 3, day: 30 }, gender: 'male' },
  { id: 'madongseok', name: 'Ma Dong-seok (Don Lee)', birth: { year: 1971, month: 3, day: 1 }, gender: 'male' },
  { id: 'leejungjae', name: 'Lee Jung-jae', birth: { year: 1972, month: 12, day: 15 }, gender: 'male' },
  { id: 'junjihyun', name: 'Jun Ji-hyun', birth: { year: 1981, month: 10, day: 30 }, gender: 'female' },
  { id: 'kimtaeri', name: 'Kim Tae-ri', birth: { year: 1990, month: 4, day: 24 }, gender: 'female' },
  { id: 'choiwooshik', name: 'Choi Woo-shik', birth: { year: 1990, month: 3, day: 26 }, gender: 'male' },
  // --- 스포츠·기타 ---
  { id: 'son', name: 'Son Heung-min', birth: { year: 1992, month: 7, day: 8 }, gender: 'male' },
  { id: 'yuna', name: 'Yuna Kim', birth: { year: 1990, month: 9, day: 5 }, gender: 'female' },
  { id: 'faker', name: 'Faker', birth: { year: 1996, month: 5, day: 7 }, gender: 'male' },
];
